# Generated by Django 5.1.3 on 2026-04-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="interview_cheatsheet",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
