# Generated by Django 5.1.5 on 2026-04-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0002_application_interview_cheatsheet"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="external_intelligence",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
